a = 10
b = 20
c = a + b
print( "Value of a + b = ", c)
c = a - b
print( "value of a - b = ", c)
c = a * b
print( "value of a * b = ", c)
c = b / a
print( "value of b / a = ", c)
c = b % a
print("value of b % a = ", c)